pobluesky/customer-inquiry-system

- backend/src/main/java/com/pobluesky/backend/domain/user/controller/UserController.java
- backend/src/main/java/com/pobluesky/backend/domain/user/dto/UserCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/user/entity/User.java
- backend/src/main/java/com/pobluesky/backend/domain/user/repository/UserRepository.java
- backend/src/main/java/com/pobluesky/backend/domain/user/service/UserService.java
- backend/src/main/java/com/pobluesky/backend/global/BaseEntity.java
- backend/src/main/java/com/pobluesky/backend/global/config/WebConfig.java
- backend/src/main/java/com/pobluesky/backend/global/error/CommonException.java
<br>
- 도메인 구조 패키지 생성
- BaseEntity 생성
<br>
- 도메인 구조의 경우 
`controller,repo,service,dto,entity` 로 구성
- BaseEntity는 모든 Entity 클래스가 상속하도록 하여 기본 생성 날짜 및 수정날짜를 가짐.
> BE chore#48 syj  도메인 구조

- frontend/config/babel.config.json
- frontend/config/webpack.config.js
- frontend/package-lock.json
- frontend/package.json
> pbs-63--chore: 패키지 수정

- .vscode/settings.json
- backend/src/main/java/com/pobluesky/backend/global/error/ErrorCode.java
<br>
- ErrorCode 충돌 해결 및 .vscode 삭제 
<br>
> Main resolve conflits

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/ProductType.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/controller/LineItemController.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/service/LineItemService.java
- backend/src/main/java/com/pobluesky/backend/domain/review/entity/Review.java
<br>
- Line Item Create 메서드명 수정 
- Product Type 추가 
- Review - isActivated 변수 삭제  
<br>
<br>
> Be refactor#82 pjh  line item domain

- backend/src/main/java/com/pobluesky/backend/domain/quality/controller/QualityController.java
<br>
- api 명세서를 보고 복수형으로 맞추기 위해 수정했습니다! (quality -> qualities)
<br>
> pbs-77--fix: api url 수정 quality -> qualities

- backend/src/main/java/com/pobluesky/backend/domain/offersheet/dto/request/OfferSheetCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/offersheet/dto/request/OfferSheetUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/offersheet/dto/response/OfferSheetResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/offersheet/entity/OfferSheet.java
- backend/src/main/java/com/pobluesky/backend/domain/offersheet/service/OfferSheetService.java
- backend/src/main/resources/data.sql
<br>
- offersheet response 피드백 반영 
<br>
<br>
> pbs-75--refactor: remark컬럼 추가, price_terms 데이터 수정

- frontend/src/components/organisms/BarChart.js
- frontend/src/components/organisms/PieChart.js
<br>
- Chart Component 추가 (수정 중)
> pbs-114--feat: Chart Components

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Inquiry.java
- backend/src/main/resources/data.sql
<br>
inquiry entity baseentity 상속
<br>
<br>
> pbs--73--chore: inquiry extends baesentity

- frontend/src/App.js
- frontend/src/assets/css/Offersheet.css
- frontend/src/components/atoms/Button.js
- frontend/src/components/mocules/Card.js
- frontend/src/components/mocules/RequestBar.js
- frontend/src/pages/inq/Inq.js
> Fe feat#114 bhj  VoC Card 컴포넌트 구현 중

- backend/build.gradle
- backend/src/main/java/com/pobluesky/backend/domain/notification/controller/NotificationController.java
- backend/src/main/java/com/pobluesky/backend/domain/quality/controller/QualityController.java
- backend/src/main/java/com/pobluesky/backend/global/config/SwaggerConfig.java
- backend/src/main/java/com/pobluesky/backend/global/error/ErrorCode.java
- backend/src/main/resources/data.sql
<br>
- Swagger-UI Setting
- Notification & Quality Controller @Operaion 추가
<br>
<br>
<br>
- [스프링부트 실행 후 접속링크] : http://localhost:8080/swagger-ui/index.html
- 테스트하고 싶은 api를 클릭하고 [Try it out] 클릭 후, parameter가 있다면 입력하시고 Request 입력 후, Execute 로 실행하시면 됩니다!
- 여유로우실 때 컨트롤러에서 @ Operation(summary = "품질검토 전체 조회") 이런 식으로 어노테이션 추가해주시면 좋을 것 같아요!
="https://github.com/user-attachments/assets/6d13b2d5-627c-4ecf-9481-49b17b602646">
- 자세한 사용 방법은 아래 링크 참고하시면 좋을 것 같아요! (**`토큰으로 로그인해서 테스트하는 방법`**, **`이미지(MultiPart File)를 입력 데이터로 받는 경우 추가 설정`** 참고)
- [Swagger-UI 사용 방법] https://velog.io/@gmlstjq123/SpringBoot-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90-Swagger-UI-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0
> Be feat#132 bjy  swagger setting

- backend/src/main/java/com/pobluesky/backend/domain/collaboration/service/CollaborationService.java
- backend/src/main/java/com/pobluesky/backend/global/config/WebConfig.java
- backend/src/main/resources/application.properties
> pbs-144--fix: Error Fix

- backend/src/main/java/com/pobluesky/backend/global/config/SecurityConfig.java
<br>
- SecurityConfig - Swagger url 허용
> pbs-145--hotfix: SecurityConfig - Swagger url 허용

- backend/src/main/java/com/pobluesky/backend/global/security/JwtTokenProvider.java
<br>
- getAuthentication key 수정 
<br>
<br>
> fix: Fixed Authentication JWT

- backend/src/main/java/com/pobluesky/backend/domain/collaboration/controller/CollaborationController.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/controller/LineItemController.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/controller/NotificationController.java
- backend/src/main/java/com/pobluesky/backend/domain/offersheet/controller/OfferSheetController.java
- backend/src/main/java/com/pobluesky/backend/domain/quality/controller/QualityController.java
- backend/src/main/java/com/pobluesky/backend/domain/review/controller/ReviewController.java
<br>
- Swagger Summary 작성
<br>
> pbs-150--feat: Swagger Summary 작성

- backend/src/main/java/com/pobluesky/backend/domain/answer/service/AnswerService.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/controller/CollaborationController.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/controller/LineItemController.java
- backend/src/main/java/com/pobluesky/backend/domain/review/controller/ReviewController.java
- backend/src/main/java/com/pobluesky/backend/domain/user/dto/request/ManagerCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/user/dto/request/ManagerUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/user/dto/response/ManagerResponseDTO.java
<br>
-  user role 
- operation
- throw exception
<br>
> pbs-157--hotfix: main - user role issue resolved

- backend/src/main/java/com/pobluesky/backend/domain/user/dto/request/CustomerCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/user/dto/request/ManagerCreateRequestDTO.java
<br>
- Customer, Manager create req dto : roles 제거
<br>
> pbs-159--hotfix: user create request roles 제거

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquiryLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Country.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Progress.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryCustom.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/response/thickplate/ThickPlateLineItemSummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/WireRodLineItem.java
<br>
- inquiry 전체 조회 refactor API에서 사용중이던 주석 코드 처리 
<br>
<br>
> pbs-167--hotfix: 주석 삭제

- backend/src/main/java/com/pobluesky/backend/domain/collaboration/entity/ColStatus.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/request/InquiryCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/request/InquiryUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquiryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquirySummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Country.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Industry.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Inquiry.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/InquiryType.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/type/wirerod/InqName.java
- backend/src/main/java/com/pobluesky/backend/domain/quality/entity/Quality.java
- backend/src/main/java/com/pobluesky/backend/domain/question/entity/QuestionStatus.java
- backend/src/main/java/com/pobluesky/backend/domain/question/entity/QuestionType.java
- backend/src/main/java/com/pobluesky/backend/domain/review/entity/ContractType.java
- backend/src/main/java/com/pobluesky/backend/domain/review/entity/Review.java
- backend/src/main/java/com/pobluesky/backend/global/config/SecurityConfig.java
- backend/src/main/resources/data.sql
<br>
- inquiry에서 erd와 함께 불필요한 속성 제거, 그에 따른 dto 변경, sql 변경
<br>
<br>
> Be refactor#169 ksy  inquiry api modify

- backend/src/main/java/com/pobluesky/backend/domain/user/controller/CustomerController.java
- backend/src/main/java/com/pobluesky/backend/domain/user/controller/ManagerController.java
- backend/src/main/java/com/pobluesky/backend/domain/user/service/CustomerService.java
- backend/src/main/java/com/pobluesky/backend/domain/user/service/ManagerService.java
- backend/src/main/java/com/pobluesky/backend/global/config/SecurityConfig.java
<br>
- customer, manager 개별 조회 API 구현
<br>
<br>
> Be feat#178 syj  user info get

- frontend/src/apis/api/notification.js
- frontend/src/assets/css/Header.css
- frontend/src/components/mocules/Header.js
- frontend/src/pages/login/Login.js
<br>
- 로그아웃 버튼 다시 나타나게 하기
<br>
이제 User 관련은 끝....(?)
> pbs-184--hotfix: error fix

- backend/src/main/java/com/pobluesky/backend/domain/user/service/SignService.java
- backend/src/main/java/com/pobluesky/backend/global/security/JwtToken.java
- backend/src/main/java/com/pobluesky/backend/global/security/JwtTokenProvider.java
<br>
- jwt 토큰에 userId 추가
<br>
<br>
<image 첨부>
<br>
> pbs-187--hotfix: jwt token + userId

- backend/src/main/java/com/pobluesky/backend/global/config/SwaggerConfig.java
<br>
- Swagger에서도 Token 으로 API 테스트 가능하도록 수정하였습니다.
<br>
1.  Swagger에서 회원가입
2. Swagger에서 로그인 -> 토큰 반환
3. 해당 토큰을 우측 상단에 있는 Authorization 에 토큰 값을 value에 넣고 Authorize 클릭
4. 테스트할 API에 Authorization 입력칸에 토큰 한번 더 넣고 -> execute
<br>
<br>
> pbs-132--fix: Swagger Token 으로 테스트 가능하도록 수정

- backend/src/main/java/com/pobluesky/backend/domain/collaboration/controller/CollaborationController.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/dto/response/CollaborationSummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/repository/CollaborationRepository.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/repository/CollaborationRepositoryCustom.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/repository/CollaborationRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/service/CollaborationService.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepository.java
- backend/src/main/java/com/pobluesky/backend/domain/question/service/QuestionService.java
<br>
-협업 목록 조회 API 정렬&조건에 맞는 페이징 처리
(기존 협업 목록 조회 API는 해당 PR로 대체되며, 헷갈릴까 지웠습니다.) 
- 사용안하고 있는 Repository 메서드 삭제 
<br>
<br>
> Be feat#124 pjh  VoC 협업 목록 조회

- backend/src/main/java/com/pobluesky/backend/domain/user/dto/request/CustomerCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/user/dto/request/ManagerCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/user/entity/Customer.java
- backend/src/main/java/com/pobluesky/backend/domain/user/entity/Manager.java
- backend/src/main/java/com/pobluesky/backend/domain/user/service/CustomerService.java
- backend/src/main/java/com/pobluesky/backend/domain/user/service/ManagerService.java
- backend/src/main/resources/data.sql
<br>
- 기존 roles 리스트에서 하나의 role만 저장하도록 String 으로 변경
- data.sql에 bcrypt 인코딩한 password, security role(user), CUSTOMER / SALES / QUALITY 데이터 추가
-  비밀번호 : 1234 !
<br>
<br>
> Be refactor#191 syj user role security

- backend/src/main/java/com/pobluesky/backend/domain/collaboration/controller/CollaborationController.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/service/CollaborationService.java
<br>
- 협업 요청 API 로직 수정
- [Before] 
기존에 A -> B 협업 요청 건이 있다면, A -> B에게 다른 QuestionId에 대한 협업 요청 불가
- [After]
A -> B에게 여러 협업 요청 가능 
<br>
> pbs-199--hotfix: 협업 요청 조건 제거

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/controller/InquiryController.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquiryLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquiryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepository.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryCustom.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/service/LineItemService.java
<br>
- inquiryResponseDTO : boolean isActivated 추가
- 담당자 inquiry 상세 조회
- 코드 정리
<br>
<br>
> Be refactor#200 syj  inquiry manager get

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/request/InquiryCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/request/InquiryUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquiryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Inquiry.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
- backend/src/main/java/com/pobluesky/backend/domain/quality/controller/QualityController.java
- backend/src/main/java/com/pobluesky/backend/domain/quality/dto/request/QualityCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/quality/dto/request/QualityReviewInfoCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/quality/entity/QualityReviewInfo.java
- backend/src/main/java/com/pobluesky/backend/domain/quality/service/QualityService.java
- backend/src/main/java/com/pobluesky/backend/domain/review/dto/request/ReviewCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/review/dto/response/ReviewResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/review/entity/Review.java
- backend/src/main/resources/data.sql
<br>
- file upload 기능을 가진 inquiry,review,quality 정리
<br>
<br>
- 기존에는 uuid를 사용하여 고유값 path를 생성하여 s3에 올렸는데 frontend에서 사용하기 번거로워서 path값과 원래 file이름 속성을 나눠 저장
> Be feat#204 ksy  fileupload modify

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquiryResponseDTO.java
<br>
- 담당자 inquiryResponse에 customerCode, email, phone 추가
<br>
<br>
> pbs-208--hotfix: Inquiry - 담당자 조회시 고객사 정보 조회 issue resolved

- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/ColdRolledLineItem.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/WireRodLineItem.java
- frontend/src/components/mocules/FileGetItem.js
- frontend/src/components/organisms/InquirySearchBox.js
- frontend/src/components/organisms/inquiry-form/FileFormItem.js
- frontend/src/components/organisms/inquiry-form/Offersheet.js
<br>
- 파일업로드 수정
- LocalDate 수정
- import 구문 수정
<br>
> pbs-209--hotfix: File 업로드, LocalDate, import 구문 수정

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquirySummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryImpl.java
<br>
- Inquiry 조회 API 응답 수정 
<br>
<br>
> pbs-212--refactor: InquirySummaryResponseDTO 속성 추가

- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/car/CarLineItemCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/car/CarLineItemUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/coldrolled/ColdRolledLineItemCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/coldrolled/ColdRolledLineItemUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/hotrolled/HotRolledLineItemCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/hotrolled/HotRolledLineItemUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/thickplate/ThickPlateLineItemCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/thickplate/ThickPlateLineItemUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/wirerod/WireRodLineItemCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/wirerod/WireRodLineItemUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/response/car/CarLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/response/coldrolled/ColdRolledLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/response/hotrolled/HotRolledLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/response/thickplate/ThickPlateLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/response/wirerod/WireRodLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/CarLineItem.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/ColdRolledLineItem.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/HotRolledLineItem.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/ThickPlateLineItem.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/WireRodLineItem.java
- backend/src/main/resources/data.sql
- frontend/src/apis/api/inquiry.js
- frontend/src/pages/inq-list/SalesManagerInqList.js
<br>
- 라인아이템 속성 및 데이터 추가
- api 수정으로 frontend 화면에 안 뿌려지는거 조금만 수정
<br>
<br>
> Be feat#213 ksy  add lineitem attribute

- backend/src/main/java/com/pobluesky/backend/domain/offersheet/dto/request/OfferSheetCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/offersheet/dto/response/OfferSheetResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/offersheet/entity/OfferSheet.java
<br>
- OfferSheet message필드 추가
- 용도: 담당자가 texteditor를 통해 전반적인 메시지 및 감사 인사나 안내 문구 작성을 위함
<br>
> Be refactor#214 pjh  offersheet col add

- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/car/CarLineItemCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/car/CarLineItemUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/coldrolled/ColdRolledLineItemCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/coldrolled/ColdRolledLineItemUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/thickplate/ThickPlateLineItemCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/thickplate/ThickPlateLineItemUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/wirerod/WireRodLineItemCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/wirerod/WireRodLineItemUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/response/car/CarLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/response/coldrolled/ColdRolledLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/response/thickplate/ThickPlateLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/response/wirerod/WireRodLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/CarLineItem.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/ColdRolledLineItem.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/WireRodLineItem.java
- backend/src/main/resources/data.sql
<br>
- line item 컬럼 변경 사항 반영
- erd 수정
- request, response dto 
- data.sql update
<br>
<br>
> Be chore#215 syj  line item add column

- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/request/car/CarLineItemCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/dto/response/car/CarLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/lineitem/entity/CarLineItem.java
- backend/src/main/resources/data.sql
<br>
- car line item : LocalDate -> String 
<br>
<br>
> pbs-216--hotfix: car loacaldate -> string

- backend/src/main/java/com/pobluesky/backend/domain/review/controller/ReviewController.java
- backend/src/main/java/com/pobluesky/backend/domain/review/dto/request/ReviewUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/review/entity/Review.java
- backend/src/main/java/com/pobluesky/backend/domain/review/service/ReviewService.java
<br>
- inquiry에서 판매 - 품질 - 다시 판매로 넘어갈 때 finalReviewText를 추가하는 것은 사실 수정이므로 PUT method 추가
<br>
<br>
<image 첨부>
<br>
> pbs-218--feat: review_put_method

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/controller/InquiryController.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/request/InquiryProgressUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquiryProgressResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Inquiry.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
- backend/src/main/java/com/pobluesky/backend/global/error/ErrorCode.java
<br>
- Inquiry Progress 상태 업데이트
- 가능한 업데이트 조건 
|기존 상태|업데이트 할 상태|
|---|---|
|접수(Receipt)|1차검토완료(First Review)|
|1차검토완료(First Review)|품질검토요청(Quality Review)|
||최종검토완료(Final Review)|
|품질검토요청(Quality Review)|최종검토완료(Final Review)|
- API 명세서 추가 
<br>
<br>
> Be feat#221 pjh inquiry progress update

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/question/controller/QuestionController.java
- backend/src/main/java/com/pobluesky/backend/domain/question/repository/QuestionRepositoryCustom.java
- backend/src/main/java/com/pobluesky/backend/domain/question/repository/QuestionRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/question/service/QuestionService.java
<br>
- Question 조회 API(담당자/고객) 조회 조건 추가 
- questionId, title 조회 조건 추가 
- 담당자의 경우 customerName 조회 조건 추가 
- title, customerName의 경우 contains로 비교
- (현재 데이터 개수 기준)100ms 이내로 동작하여 검색하는데 문제 없지만, 추후 결과가 많아져 성능에 문제가 있다면 ES나 쿼리 최적화 고려중입니다
<br>
<br>
> Be refactor#219 pjh  add question filtering

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/controller/InquiryController.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryCustom.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
<br>
- Inquiry 조회 페이지 조건 추가
- industry: 정해진 타입에 따라 데이터 반환
- salesPerson: 특정 단어 입력 시 데이터 반환(contains 사용) 
<br>
<br>
> Be refactor#222 pjh inquiry sorting add

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/controller/InquiryController.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/request/InquiryCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/request/InquiryProgressUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/request/InquiryUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquiryLineItemResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquirySummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Inquiry.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Progress.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
- backend/src/main/java/com/pobluesky/backend/global/error/ErrorCode.java
<br>
- 기존 request에 progress 를 넘겨 변경하는 방식에서 버튼을 클릭시 바로 다음 단계로 넘어가게 변경
- inquiry 수정 기능 
- 수정은 접수 전, 제출 단계에서만 가능하게 구현
<br>
<br>
> Be feat#223 syj  inquiry update

- frontend/src/components/organisms/inquiry-form/InquiryHistoryForm.js
- frontend/src/components/organisms/inquiry-form/InquiryHistoryFormItem.js
- frontend/src/pages/inq-item/LineItemTableForm.js
- frontend/src/pages/inq-list/CustomerInqTableList.js
- frontend/src/pages/inq-list/QualityManagerInqTableList.js
- frontend/src/pages/inq-list/SalesManagerInqTableList.js
<br>
- 병합 과정에서 생성된 충돌 알림 기호가 남아있어 해당 부분 삭제하였습니다.
> pbs-230--fix: 머지 과정에서 생성된 불필요한 기호 삭제

- frontend/src/assets/css/Auth.css
- frontend/src/components/molecules/Header.js
- frontend/src/components/molecules/JoinButton.js
- frontend/src/components/molecules/QuestionModal.js
- frontend/src/pages/join/Join.js
- frontend/src/pages/voc-main/VocMain.js
- frontend/src/utils/actions.js
- frontend/src/utils/validation.js
<br>
- 회원가입 로직 수정
- Bad User 유입 상황 가정 하에 에러 처리 완료
> pbs-229--feat: 회원가입 로직 수정

- frontend/src/assets/css/Header.css
- frontend/src/components/molecules/Header.js
- frontend/src/pages/inq-main/InqMain.js
- frontend/src/pages/intro/section/FirstIntro.js
- frontend/src/pages/login/Login.js
- frontend/src/pages/voc-main/VocMain.js
- frontend/src/utils/actions.js
<br>
- 유저 권한에 따른 페이지 접근 권한 변경
- 상세 메뉴 구현
> Fe feat#229 bhj  qna col

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
<br>
- RECEIPT -> SUBMIT
<br>
<br>
> pbs-238--hotfix: 담당자 배정 이슈 해결

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
> pbs-239--hotfix: 담당자 배정 이슈 해결

- frontend/src/apis/utils/inquiryUtils.js
- frontend/src/assets/css/Inquiry.css
- frontend/src/components/atoms/InqPath.js
- frontend/src/components/atoms/ManagerInqPath.js
- frontend/src/components/organisms/inquiry-form/CollapsibleTable.js
- frontend/src/components/organisms/inquiry-form/CustomerTable.js
- frontend/src/components/organisms/inquiry-form/InquiryNewForm.js
- frontend/src/components/organisms/inquiry-form/InquirySearchBox.js
- frontend/src/components/organisms/inquiry-form/Row.js
- frontend/src/pages/inq-form/CustomerInqForm.js
- frontend/src/pages/inq-item/CustomerInqItem.js
- frontend/src/pages/inq-item/QualityManagerInqItem.js
- frontend/src/pages/inq-item/SalesManagerInqItem.js
- frontend/src/pages/inq-list/CustomerInqTableList.js
- frontend/src/pages/inq-list/QualityManagerInqTableList.js
- frontend/src/pages/inq-list/SalesManagerInqTableList.js
- frontend/src/pages/inq-main/InqMain.js
- frontend/src/utils/actions.js
> pbs-232--hotfix: 테스트 중 핫픽스 해결

- frontend/src/components/molecules/LineItemToggleBar.js
- frontend/src/components/molecules/Modal.js
- frontend/src/components/organisms/inquiry-form/CustomerTable.js
- frontend/src/components/organisms/inquiry-form/InquiryHistoryForm.js
- frontend/src/pages/inq-form/CustomerInqForm.js
- frontend/src/pages/inq-item/CustomerInqItem.js
<br>
- 과거이력조회에서 선택한 라인아이템을 바로 자동 입력 가능하게 구현
<br>
<br>
<br>
<br>
<br>
> pbs-295--feat: 과거이력조회로 데이터 전달 기능 완료

- backend/src/main/java/com/pobluesky/backend/domain/notification/controller/NotificationController.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/repository/CustomerNotificationRepository.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/repository/ManagerNotificationRepository.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/service/NotificationService.java
- frontend/src/apis/api/notification.js
- frontend/src/components/molecules/Header.js
- frontend/src/components/molecules/NotificationModal.js
<br>
- 읽지 않은 알림 갯수 totalElements 추가
- 읽지 않은 알림 갯수 Header.js에 연동
<br>
<br>
- 희진사마가 만들어주신 헤더 속 기깔난 알림 아이콘에 연동을 했습니다.
- 희진사마 감사합니다^.^
<br>
<br>
> Be feat#299 bjy  notification count

- frontend/src/assets/css/Inquiry.css
- frontend/src/assets/css/animations.css
- frontend/src/components/atoms/Chip.js
- frontend/src/components/molecules/BorderLinearProgress.js
- frontend/src/components/molecules/Header.js
- frontend/src/components/molecules/NotificationModal.js
- frontend/src/components/molecules/StepTracker.js
- frontend/src/components/organisms/inquiry-form/CollapsibleTable.js
- frontend/src/components/organisms/inquiry-form/CustomerTable.js
- frontend/src/components/organisms/inquiry-form/InquiryHistoryFormItem.js
- frontend/src/components/organisms/inquiry-form/Row.js
<br>
- Inquiry 테이블 수정
- InquiryType 뱃지 형태로 변경
- Inquiry 진행률 progress bar 추가
- Inquiry 진행률 progress bar hover 시, 현재 process 컴포넌트 뜨도록 추가
<br>
<br>
<br>
> Fe feat#298 bjy  inquiry progress development

- frontend/src/assets/css/Voc.css
- frontend/src/components/atoms/VocButton.js
- frontend/src/components/molecules/ColResModal.js
- frontend/src/components/molecules/Header.js
- frontend/src/components/molecules/QuestoinInquirySearchModal.js
- frontend/src/components/organisms/AnswerInput.js
- frontend/src/components/organisms/ColReqInput.js
- frontend/src/components/organisms/QuestionInput.js
- frontend/src/components/organisms/QuestionTypeSelector.js
- frontend/src/components/organisms/QuestionViewer.js
- frontend/src/components/templates/AnswerForm.js
- frontend/src/components/templates/QuestionDashboard.js
- frontend/src/components/templates/QuestionForm.js
- frontend/src/pages/intro/Intro.js
- frontend/src/pages/join/Join.js
- frontend/src/pages/login/Login.js
- frontend/src/pages/voc-form/VocColForm.js
- frontend/src/pages/voc-form/VocQuestionForm.js
- frontend/src/pages/voc-list/VocColList.js
- frontend/src/pages/voc-list/VocQuestionList.js
- frontend/src/utils/actions.js
- frontend/src/utils/validation.js
<br>
- Header 경로 이동 로직 수정
- VoC 새로고침 이슈 해결
- VoC (협업 제외) 리팩토링 완료
> Fe feat#310 bhj voc question

- frontend/src/components/molecules/Header.js
> pbs-310--hotfix: Header 대시보드 화면에서 Header 미출력 버그 해결

- frontend/src/App.js
- frontend/src/assets/css/Chart.css
- frontend/src/components/organisms/InquiryProductProgressChart.js
- frontend/src/components/organisms/InquiryProgressCountChart.js
- frontend/src/components/organisms/QuestionInput.js
- frontend/src/components/organisms/QuestionTypeSelector.js
<br>
- Chart API 연동 완료
- props 상세 조절
- 추후 VoC 답변 및 협업 건수까지 추가해서 6개의 차트를 만들까 합니다.
> Fe refactor#320 bhj  chart

- frontend/src/components/organisms/inquiry-form/Offersheet.js
- frontend/src/pages/inq-item/CustomerInqItem.js
- frontend/src/pages/inq-list/CustomerInqTableList.js
<br>
- 고객사 Inquiry 상세조회 로컬스토리지 추가
- 오퍼시트 message 컬럼 기본값 추가
<br>
<br>
> Fe hotfix#297 bjy  local storage

- backend/src/main/java/com/pobluesky/backend/domain/notification/repository/CustomerNotificationRepository.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/repository/ManagerNotificationRepository.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/service/NotificationService.java
- frontend/src/components/organisms/inquiry-form/Row.js
- frontend/src/pages/inq-form/CustomerInqForm.js
- frontend/src/pages/inq-item/CustomerInqItem.js
- frontend/src/pages/inq-item/QualityManagerInqItem.js
- frontend/src/pages/inq-item/SalesManagerInqItem.js
- frontend/src/pages/inq-list/SalesManagerInqTableList.js
<br>
- [BE] 알림 API 세부 수정
- [BE] 읽지 않은 알림 최신순 정렬
- [FE] Inquiry 고객사/담당자 알림 Progress 별 연동 완료
<br>
<br>
1. **`To. 고객사`**
1. ✅ Inquiry 작성 후, **`[검토의뢰]`** 버튼 클릭 시 : “김민준님의 Inquiry가 접수되었습니다.” → Progress **`문의제출`**
2. ✅ 고객사 Inquiry 수정되었을 때 : “김민준님의 Inquiry가 수정되었으며, 담당자 배정 시 수정이 불가합니다.”
3. ✅ 판매담당자가 조회 리스트에서 Inquiry 체크 후, **`담당자 배정`** 클릭 시 : “김민준님의 Inquiry 3번 담당자가 배정되었습니다.” → Progress **`문의접수`**
4. 견적 문의인 경우,
1. ✅ 판매담당자가 **`[1차검토완료]`** 버튼 클릭 시 : “김민준님의 문의 1차 검토가 완료되었습니다.” → Progress **`1차검토완료`**
2. ✅ 판매담당자가 **`[최종검토완료]`** 버튼 클릭 시 : “김민준님의 문의 최종 검토가 완료되었습니다. 최종 검토 내용과 OfferSheet를 확인해 주세요.” → Progress **`최종검토완료`**
5. 견적 + 품질 문의인 경우,
1. ✅ 판매담당자가 **`[1차검토완료]`** 버튼 클릭 시 : “김민준님의 문의 1차 검토가 완료되었습니다.” → Progress **`1차검토완료`**
2. ✅ 판매담당자가 **`[품질검토요청]`** 버튼 클릭 시 : “김민준님의 문의는 현재 품질 검토 진행 중입니다.” → Progress …
> Fe feat#301 bjy  notification

- backend/src/main/java/com/pobluesky/backend/domain/answer/controller/MobileAnswerController.java
- backend/src/main/java/com/pobluesky/backend/domain/answer/dto/response/MobileAnswerSummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/answer/service/AnswerService.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/controller/InquiryController.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/controller/MobileInquiryController.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/MobileInquiryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/MobileInquirySummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/response/MobileQuestionSummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/user/controller/ManagerController.java
- backend/src/main/java/com/pobluesky/backend/domain/user/controller/MobileUserController.java
- backend/src/main/java/com/pobluesky/backend/domain/user/dto/response/MobileManagerResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/user/entity/UserRole.java
- backend/src/main/java/com/pobluesky/backend/domain/user/service/ManagerService.java
- backend/src/main/java/com/pobluesky/backend/global/config/SecurityConfig.java
<br>
- 모바일 manager response dto. api
- 모바일 question, answer response  answer dto, api
- 모바일 5가지 타입별  lineitem response  dto 및 api
<br>
<br>
> Be feat#341 syj  mobile mypage api

- backend/src/main/java/com/pobluesky/backend/domain/answer/controller/AnswerController.java
- backend/src/main/java/com/pobluesky/backend/domain/answer/dto/request/AnswerUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/answer/dto/response/AnswerResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/answer/entity/Answer.java
- backend/src/main/java/com/pobluesky/backend/domain/answer/service/AnswerService.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/request/InquiryUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/controller/QuestionController.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/request/QuestionCreateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/request/QuestionUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/response/QuestionResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/response/QuestionSummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/entity/Question.java
- backend/src/main/java/com/pobluesky/backend/domain/question/repository/QuestionRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/question/service/QuestionService.java
- backend/src/main/java/com/pobluesky/backend/global/error/ErrorCode.java
> Be feat#345 bhj qna put/delete

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/IntegratedOcrGptService.java
<br>
- inquiry 내역 등록 car prompt 수정 
<br>
<br>
- prompt에 자세한 내용을 전달해도, 학습을 시키지 않으니 응답률에 있어 저조한 경우도 발생하네요. 
모든 케이스를 지금 단계에서 잡기보다 추후 하나씩 더해가려합니다.
> pbs-291--refactor: car prompt 수정

- backend/src/main/java/com/pobluesky/backend/domain/collaboration/controller/CollaborationController.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/repository/CollaborationRepositoryCustom.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/repository/CollaborationRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/service/CollaborationService.java
<br>
- 협업 목록 조회 페이징 처리 API 추가  
- 기존 페이징 없는 API 삭제 
<br>
<br>
> Be refactor#305 pjh 협업 목록 조회 페이징 처리

- backend/src/main/java/com/pobluesky/backend/domain/answer/controller/AnswerController.java
- backend/src/main/java/com/pobluesky/backend/domain/answer/repository/AnswerRepository.java
- backend/src/main/java/com/pobluesky/backend/domain/answer/service/AnswerService.java
- backend/src/main/java/com/pobluesky/backend/domain/question/controller/QuestionController.java
- backend/src/main/java/com/pobluesky/backend/domain/question/repository/QuestionRepositoryCustom.java
- backend/src/main/java/com/pobluesky/backend/domain/question/repository/QuestionRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/question/service/QuestionService.java
- backend/src/main/resources/data.sql
- frontend/src/components/organisms/QuestionList.js
- frontend/src/components/templates/QuestionDashboard.js
<br>
- 월별, 담당자별 VoC 답변 처리 건수 조회 API 추가하였습니다.
- [해당 피드백](https://github.com/pobluesky/customer-inquiry-system/pull/192#discussion_r1749773260) 반영하여 메서드 분리 및 명칭 수정하였습니다. 추후에 리팩토링 고려중입니다.
- 질문 게시판 페이징 처리 API 연동 완료하였습니다.
> Be feat#349 bhj voc dashboard api & method extract

- frontend/src/components/organisms/ColTable.js
<br>
- 협업 페이지 API response를 저장하는 코드를 수정하였습니다.
> Fe feat#347 bhj voc col

- backend/src/main/java/com/pobluesky/backend/domain/chat/controller/ChatController.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/dto/request/ChatRequestMsgDto.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/dto/response/ChatCompletionDto.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/dto/response/OrderInquiryResponse.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/dto/response/ProductInquiryResponse.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/dto/response/RegistrationInquiryResponse.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/entity/type/ChatInquirySubType.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/entity/type/ChatInquiryType.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/service/ChatbotService.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/service/GptPromptService.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/service/IntegratedOcrGptService.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/service/OcrService.java
- backend/src/main/java/com/pobluesky/backend/domain/chat/service/PdfConversionService.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/controller/InquiryController.java
- backend/src/main/java/com/pobluesky/backend/global/error/ErrorCode.java
<br>
- chatbot api 구현(문의타입별 기본 질문)  
<br>
<br>
프론트단에서 테스트하면서 개발하기 위해 우선 main 브랜치에 머지 후, 리팩토링 예정입니다.
> Be feat#353 pjh voc chatbot api

- backend/.gitignore
- backend/build.gradle
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/MobileInquiryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/MobileInquirySummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Industry.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/InquiryType.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/ProductType.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/controller/MobileNotificationController.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/controller/NotificationController.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/dto/FcmMessage.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/dto/response/MobileNotificationResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/entity/Notification.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/repository/ManagerNotificationRepository.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/service/FirebaseCloudMessageService.java
- backend/src/main/java/com/pobluesky/backend/domain/notification/service/NotificationService.java
- backend/src/main/java/com/pobluesky/backend/global/config/FirebaseConfig.java
- backend/src/main/java/com/pobluesky/backend/global/config/SecurityConfig.java
<br>
모바일 알림 스프링부트 서버
1. api, service
2. fcm gradle 및 config -> 팝업 
3. enum 클래스 들 korean Name 추가
<br>
<br>
> Be feat#359 syj mobile notification api

- backend/src/main/java/com/pobluesky/backend/domain/chat/service/ChatbotService.java
- backend/src/main/resources/prompt/chatbot_prompt.txt
<br>
- 챗봇 API prompt 강화
- logger 삭제 
- 버튼 식 기본 응답 수정 
<br>
<br>
> Be refactor#374 pjh  voc chatbot response fix

- frontend/src/assets/css/FileUpload.css
- frontend/src/components/molecules/FileUploadModal.js
- frontend/src/components/molecules/LineItemToggleBar.js
- frontend/src/components/organisms/inquiry-form/InquiryHistoryForm.js
- frontend/src/pages/inq-form/CustomerInqForm.js
- frontend/src/utils/actions.js
<br>
- OCR 로딩 수정
- OCR 제품유형 미 선택시 경고 처리
<br>
<br>
> Fe refactor#300 bjy  ocr loading

- backend/.gitignore
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/controller/InquiryController.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquiryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquirySummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryCustom.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
<br>
- 고객/담당자 inquiry 조회 API 내 `생성일자` 응답 필드 추가 
- 고객 inquiry 상세 조회 API 내 `생성일자` 응답 필드 추가 
<br>
<br>
> Be refactor#373 pjh inquiry 조회/상세조회 response fix

- backend/src/main/java/com/pobluesky/backend/domain/user/entity/Department.java
- backend/src/main/java/com/pobluesky/backend/domain/user/entity/UserRole.java
- frontend/src/assets/css/Voc.css
- frontend/src/components/molecules/ColFindManagerModal.js
- frontend/src/components/molecules/QuestionInquirySearchModal.js
- frontend/src/components/organisms/ColFindManagerButton.js
- frontend/src/pages/join/Join.js
<br>
- Manager Department ENUM 수정
> Be feat#416 bhj dept

- frontend/src/apis/api/collaboration.js
- frontend/src/components/organisms/ColTable.js
- frontend/src/components/templates/ColResForm.js
> pbs-398--feat: 협업 조회 페이징 연동

- backend/src/main/java/com/pobluesky/backend/domain/question/dto/response/MobileQuestionSummaryResponseDTO.java
<br>
- 모바일 question detail dto에 inquiryId 추가
<br>
<br>
> Be feat#413 syj mobile inquiry no add

- frontend/src/components/organisms/ColReqInput.js
<br>
- `const response` 누락되어 추가하였습니다.
> pbs-399--fix: 코드 누락 추가

- backend/src/main/java/com/pobluesky/backend/domain/answer/controller/AnswerController.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/controller/CollaborationController.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/repository/CollaborationRepository.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/service/CollaborationService.java
- frontend/src/assets/css/Voc.css
> Be feat#402 bhj dashboard

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/InquirySummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryImpl.java
- backend/src/main/resources/data.sql
<br>
- inquiry 조회 response 수정 
- salesManager, qualityManager 부서 추가 
- data.sql 데이터 수정
- Manager 부서명 수정 
<br>
<br>
> Be refactor#454 pjh  inquiry summary dto fix

- backend/build.gradle
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/controller/CollaborationController.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/service/CollaborationService.java
- backend/src/main/java/com/pobluesky/backend/domain/file/service/FileService.java
- backend/src/main/java/com/pobluesky/backend/domain/question/controller/QuestionController.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/response/QuestionResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/response/QuestionSummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/entity/Question.java
- backend/src/main/java/com/pobluesky/backend/domain/question/repository/QuestionRepositoryCustom.java
- backend/src/main/java/com/pobluesky/backend/domain/question/repository/QuestionRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/question/service/QuestionService.java
- backend/src/main/resources/data.sql
- frontend/src/apis/api/collaboration.js
- frontend/src/assets/css/Voc.css
- frontend/src/components/molecules/Header.js
- frontend/src/components/organisms/AnswerInput.js
- frontend/src/components/organisms/ColReqInput.js
- frontend/src/components/organisms/ColResInput.js
- frontend/src/components/organisms/ColSearchInput.js
- frontend/src/components/organisms/ColTable.js
- frontend/src/components/organisms/QuestionFilterInput.js
- frontend/src/components/templates/AnswerForm.js
- frontend/src/components/templates/ColDashboard.js
- frontend/src/components/templates/QuestionDashboard.js
- frontend/src/components/templates/QuestionForm.js
<br>
- Question 도메인에 Entity 추가하여 협업 상태 확인할 수 있도록 하였습니다.
> Fe feat#402 bhj voc col update

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/repository/InquiryRepositoryImpl.java
<br>
- quality manager inquiry 조회 dto 추가 
- sales, quality manager 부서 추가 
<br>
<br>
> pbs-454--refactor: quality manager 부서 추가

- backend/src/main/java/com/pobluesky/backend/domain/answer/dto/request/AnswerUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/answer/service/AnswerService.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/dto/request/CollaborationModifyRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/dto/request/CollaborationUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/service/CollaborationService.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/request/QuestionUpdateRequestDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/response/QuestionResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/service/QuestionService.java
- frontend/src/App.js
- frontend/src/apis/api/question.js
- frontend/src/components/molecules/Header.js
- frontend/src/components/organisms/AnswerInput.js
- frontend/src/components/organisms/ColReqViewer.js
- frontend/src/components/organisms/ColResInput.js
- frontend/src/components/organisms/ColResViewer.js
- frontend/src/components/organisms/ColTable.js
- frontend/src/components/organisms/QuestionInput.js
- frontend/src/components/templates/ColResForm.js
- frontend/src/context/auth/AuthContext.js
> Fe feat#437 bhj voc file

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/controller/MobileInquiryController.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/MobileInquiryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/dto/response/MobileInquirySummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Industry.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/InquiryType.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/ProductType.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/entity/Progress.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
- backend/src/main/java/com/pobluesky/backend/domain/question/controller/MobileQuestionController.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/response/MobileQuestionSummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/entity/QuestionStatus.java
- backend/src/main/java/com/pobluesky/backend/domain/question/entity/QuestionType.java
- backend/src/main/java/com/pobluesky/backend/domain/question/repository/QuestionRepositoryCustom.java
- backend/src/main/java/com/pobluesky/backend/domain/question/repository/QuestionRepositoryImpl.java
- backend/src/main/java/com/pobluesky/backend/domain/question/service/QuestionService.java
- backend/src/main/java/com/pobluesky/backend/domain/review/controller/MobileReviewController.java
- backend/src/main/java/com/pobluesky/backend/domain/review/dto/response/ReviewResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/review/entity/SalesInfo.java
- backend/src/main/java/com/pobluesky/backend/domain/review/service/ReviewService.java
- backend/src/main/java/com/pobluesky/backend/global/config/SecurityConfig.java
<br>
-  Inquiry 검색
- 문의 검색
- Inquiry 상세에 담당자 검토 조회
- enum에 한글명 추가 
<br>
<br>
> Be feat#408 syj mobile review server

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
<br>
-Inquiry Service 메서드 충돌 해결 
<br>
> pbs-454--hotfix: inquiryService 충돌 해결

- backend/src/main/resources/data.sql
<br>
- data.sql inquiry & inquiry log 데이터 수정 
<br>
> pbs-466--hotfix: inquiry log, inquiry 데이터 수정

- frontend/src/assets/css/Header.css
- frontend/src/components/molecules/DepartmentInquiryCount.js
- frontend/src/components/molecules/FileGetItem.js
- frontend/src/components/molecules/Modal.js
- frontend/src/components/molecules/NotificationModal.js
- frontend/src/components/molecules/RequestBar.js
- frontend/src/components/organisms/inquiry-form/CustomerTable.js
- frontend/src/components/organisms/inquiry-form/Offertable.js
- frontend/src/components/organisms/inquiry-form/quality-form/QualityForm.js
- frontend/src/components/organisms/inquiry-form/quality-form/QualityReviewTextForm.js
- frontend/src/components/organisms/inquiry-form/quality-form/QualityText.js
- frontend/src/components/organisms/inquiry-form/review-form/FinalReviewTextForm.js
- frontend/src/components/organisms/inquiry-form/review-form/ReviewText.js
- frontend/src/components/organisms/inquiry-form/review-form/ReviewTextForm.js
- frontend/src/components/organisms/inquiry-form/review-form/SalesInfoForm.js
- frontend/src/pages/inq-item/QualityManagerInqItem.js
- frontend/src/pages/inq-item/SalesManagerInqItem.js
<br>
- 담당자 입력 칸 필수값 처리 추가
<br>
<br>
> Fe feat#448 bjy  inquiry test fix

- frontend/src/assets/css/Chart.css
- frontend/src/components/molecules/MyInquiryList.js
- frontend/src/pages/dashboard/DashBoard.js
> Fe hotfix#459 bhj  dashboard

- frontend/src/components/molecules/ToggleBar.js
- frontend/src/components/organisms/inquiry-form/InquiryHistoryForm.js
- frontend/src/pages/inq-item/QualityManagerInqItem.js
<br>
- 품질 path 수정
- slice 에러 수정
<br>
<br>
> Fe fix#449 bjy  inq quality path

- backend/src/main/java/com/pobluesky/backend/domain/inquiry/controller/InquiryController.java
- backend/src/main/java/com/pobluesky/backend/domain/inquiry/service/InquiryService.java
<br>
- 품질 담당자 배정 서비스 로직 수정
- 품질 담당자 배정 -> progress 업데이트 -> `log 생성`( new 🌟)
<br>
<br>
<image 첨부>
<br>
> pbs-460--hotfix: 품질 담당자 배정 시 로그 안 찍히는 이슈 해결

- backend/src/main/java/com/pobluesky/backend/domain/user/controller/ManagerController.java
- backend/src/main/java/com/pobluesky/backend/domain/user/service/ManagerService.java
- frontend/src/apis/api/manager.js
- frontend/src/components/molecules/RequestBar.js
- frontend/src/pages/inq-form/CustomerInqForm.js
- frontend/src/pages/inq-item/QualityManagerInqItem.js
- frontend/src/pages/inq-item/SalesManagerInqItem.js
<br>
- 고객사, 판매담당자, 품질담당자 알림 추가
- 알림 발송 시, 담당자 이름 조회를 위한 담당자 상세조회 api 세부 수정
(담당자 본인이 본인 정보만 조회 가능하던 것을 타 담당자도 조회 가능하도록 수정)
<br>
<br>
> Fe fix#449 bjy  manager notification fix

- backend/src/main/java/com/pobluesky/backend/domain/answer/entity/Answer.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/controller/CollaborationController.java
- backend/src/main/java/com/pobluesky/backend/domain/collaboration/service/CollaborationService.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/response/QuestionResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/dto/response/QuestionSummaryResponseDTO.java
- backend/src/main/java/com/pobluesky/backend/domain/question/entity/Question.java
- backend/src/main/java/com/pobluesky/backend/domain/question/repository/QuestionRepositoryImpl.java
- frontend/src/apis/api/collaboration.js
- frontend/src/components/organisms/AnswerInput.js
- frontend/src/components/organisms/ColReqInput.js
- frontend/src/components/templates/AnswerForm.js
- frontend/src/components/templates/ColResForm.js
- frontend/src/components/templates/QuestionDashboard.js
<br>
- Question 테이블에서 col_id 삭제 (지속적인 에러로,,, col_id는 question 테이블에서 철수시켰습니다.)
- 이로 인해 발생하는 프론트 에러를 수정하였습니다.
- Question 도메인에서 협업 여부를 판단하는 방법은 `협업 중이면 pass`, `협업 진행되지 않았으면 에러 출력`으로 변경하였습니다.
> pbs-453--feat: Question 테이블 col_id 삭제 및 로직 수정

- frontend/src/components/organisms/QuestionViewer.js
<br>
- Question 페이지에서 새 탭으로 Inquiry 페이지를 조회할 경우에 체번되는 로직을 수정하였습니다.
> pbs-453--fix: Question 페이지에서 Inquiry 체번 로직 수정

- frontend/src/components/molecules/QuestionInquirySearchModal.js
- frontend/src/components/organisms/AnswerInput.js
- frontend/src/components/organisms/ColReqInput.js
- frontend/src/components/organisms/ColResInput.js
- frontend/src/components/organisms/QuestionViewer.js
<br>
- 협업 요청 취소하면 페이지 리로딩
- Question 페이지에서 조회하는 Inquiry 체번 하이퍼링크 수정
> Fe feat#453 bhj  voc path

- frontend/src/components/molecules/FileUploadModal.js
- frontend/src/components/organisms/inquiry-form/InquiryHistoryForm.js
- frontend/src/pages/inq-item/CustomerInqItem.js
- frontend/src/pages/inq-item/SalesManagerInqItem.js
<br>
- 라인아이템 OCR 파일 업로드 응답 속도에 따라 완료하도록 수정했습니다.
- 라인아이템 파일 업로드 로직 변경(*전체 삭제 시에도 가능, 이제 행을 지우지 않아도 파일 업로드 가능함. 행 지우지 않았을 시 파일 업로드를 통해서도 행이 추가됨)
- 라인아이템 텍스트 Input에 한 글자 지워지지 않음 이슈 해결
- 품질검토요청 리다이렉트 수정
<br>
<br>
> Fe fix#462 bjy issue fix

- frontend/src/components/molecules/FileUploadModal.js
> pbs-463--hotfix: 업로드 에러

- backend/src/main/java/com/pobluesky/backend/domain/collaboration/dto/response/CollaborationDetailResponseDTO.java
- frontend/src/components/organisms/AnswerInput.js
- frontend/src/components/organisms/ColReqViewer.js
- frontend/src/components/organisms/ColResViewer.js
<br>
- 질문 삭제 불가 에러 수정
- 협업 페이지 날짜 추가
> Fe feat#453 bhj error fix

- frontend/src/components/molecules/LineItemToggleBar.js
> pbs-develop--hotfix: 정상 데이터 오류 처리 이슈 수정
